version: '3.8'

services:
  postgres:
    build:
      context: ./postgres
    image: samiassiakh/postgresql-alpine:latest
    environment:
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend


volumes:
  db_data:

networks:
  backend:
    name: backend
