version: '3.8'

services:
  symfony:
    build:
      context: ./symfony
    image: wardark/symfony-alpine:latest
    volumes:
      - ./symfony:/mon_projet
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - backend
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-test}@postgres:5432/${POSTGRES_DB:-postgres}

  composer:
    build:
      context: ./composer
    image: wardark/composer-alpine:latest
    volumes:
      - ./symfony/:/volume/mon_projet
    networks:
      - backend

  adminer:
    build:
      context: ./adminer
    image: moussastraore/adminer-alpine:latest
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - backend

networks:
  backend:
    external: true
